version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5000:5000"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://portfolio_user:8c7m40zmsldproq1@db:5432/portfolio?schema=public
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=portfolio_user
      - POSTGRES_PASSWORD=8c7m40zmsldproq1
      - POSTGRES_DB=portfolio
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
